repos:
-   repo: local
    hooks:
    -   id: branch-needs-jira
        name: Branch name includes Jira ticket
        entry: branch-needs-jira
        language: system
        pass_filenames: false
        always_run: true
    -   id: message-needs-jira
        name: Prepend Jira ticket to commit message
        entry: message-needs-jira
        language: system
        pass_filenames: true
        always_run: true
        stages: [prepare-commit-msg, commit-msg]
    -   id: pytest
        name: Run unit tests
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
