repos:
-   repo: local
    hooks:
    -   id: branch-needs-jira
        name: Branch name includes Jira ticket
        entry: branch-needs-jira
        language: system
        pass_filenames: false
        always_run: true
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
